name: shopping_ui
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  device_preview: ^1.2.0
  #Utility Packages
  http: ^1.1.0
  intl: 0.19.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  cupertino_icons: ^1.0.8

  #Icon Package
  iconsax: ^0.0.8

  #State Mangement
  get: ^4.6.5
  carousel_slider: ^5.1.1
  flutter_localizations:
        sdk: flutter
  easy_localization: ^3.0.7+1
  restart_app: ^1.3.2
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.6

  flutter_lints: ^5.0.0

flutter:
  

  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/
    - assets/translations/
    - assets/json/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Suwannaphum
      fonts:
        - asset: assets/fonts/Suwannaphum-Thin.ttf
          weight: 100
        - asset: assets/fonts/Suwannaphum-Light.ttf
          weight: 300
        - asset: assets/fonts/Suwannaphum-Regular.ttf
          weight: 400
        - asset: assets/fonts/Suwannaphum-Bold.ttf
          weight: 700
        - asset: assets/fonts/Suwannaphum-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
